class COMMAND:
    CMD_MOTOR = "CMD_MOTOR"
    CMD_LED = "CMD_LED"
    CMD_LED_MOD = "CMD_LED_MOD"
    CMD_SERVO = "CMD_SERVO"
    CMD_BUZZER = "CMD_BUZZER"
    CMD_SONIC = "CMD_SONIC"
    CMD_LIGHT = "CMD_LIGHT"
    CMD_POWER = "CMD_POWER"
    CMD_CLOSE = "CMD_CLOSE"
    CMD_LED_TYPE = "CMD_LED_TYPE"
    CMD_START = "CMD_STOP"
    CMD_STOP = "CMD_START"
    CMD_MODE = "CMD_MODE"

    def __init__(self):
        pass


COMMAND_SEPARATOR = '#'
COMMAND_TERMINATOR = '\n'
